export default {
  info: {
    id: 333,
    name: 'Kate',
    surname: 'Jamezi-Liamson',
    fullName: 'Kate Jamezi-Liamson',
    photo: require('@assets/images/profile_picture.png'),
    bio: 'I am an Experience Designer with a deep passion for travel around the world, cars, trains, snowboarding and luxury yachts',
    rating: '4.98',
    reviews: 402,
    followers: 555,
    following: 113,
    hostYear: 2023,
    mail: 'katej@gmail.com',
    validNumber: true,
    validEmail: true,
  },
  languages: ['English', 'German', 'French'],
  accounts: [
    {
      platform: 'Instagram',
      link: 'https://www.instagram.com',
    },
    {
      platform: 'Linkedin',
      link: 'https://www.linkedin.com',
    },
    {
      platform: 'visitphuket.com',
      link: 'https://www.linkedin.com',
    },
    {
      platform: 'Github',
      link: 'https://www.github.com',
    },
    {
      platform: 'Twitter',
      link: 'https://www.twitter.com',
    },
    {
      platform: 'Facebook',
      link: 'https://www.instagram.com',
    },
    {
      platform: 'Tiktok',
      link: 'https://www.tiktok.com',
    },
    {
      platform: 'travel.com',
      link: 'https://www.travel.com',
    },
  ],
  activities: {
    listed: [
      {
        title: 'December',
        data: [
          {
            id: 1,
            title: 'Alla scoperta dei produttori di vino altoatesini in ebike',
            photo: require('@assets/images/bike.png'),
            date: '02/12/2023',
            business: true,
            duration: '3 days',
            rating: '3.88',
            review: 17,
            price: 'FREE',
            places: ['Utrecht', 'Keukenhof'],
            isFavorite: false,
          },
          {
            id: 2,
            title: 'Weekend ride',
            photo: require('@assets/images/ride.png'),
            date: '15/12/2024',
            new: true,
            business: false,
            duration: '5 hours',
            rating: null,
            review: null,
            price: 'From CHF75/person',
            places: ['Utrecht'],
            isFavorite: true,
          },
        ],
      },
      {
        title: 'January',
        data: [
          {
            id: 3,
            title: 'Hiking',
            photo: require('@assets/images/hiking.jpg'),
            date: '14/01/2024',
            new: true,
            business: false,
            duration: '5 hours',
            rating: null,
            review: null,
            price: 'From CHF75/person',
            places: ['Utrecht'],
            isFavorite: true,
          },
        ],
      },
    ],
    booked: [
      {
        title: 'March',
        data: [
          {
            id: 4,
            title: 'Desert Safari Dubai',
            photo: require('@assets/images/safari.jpg'),
            date: '02/03/2023',
            business: true,
            duration: '3 days',
            rating: '3.88',
            review: 17,
            price: 'FREE',
            places: ['Dubai'],
            isFavorite: false,
          },
          {
            id: 5,
            title: 'Rafting',
            photo: require('@assets/images/rafting.jpg'),
            date: '15/03/2024',
            new: true,
            business: false,
            duration: '5 hours',
            rating: null,
            review: null,
            price: 'From CHF75/person',
            places: ['Utrecht'],
            isFavorite: true,
          },
        ],
      },
      {
        title: 'April',
        data: [
          {
            id: 6,
            title: 'Hiking',
            photo: require('@assets/images/hiking.jpg'),
            date: '15/04/2024',
            new: true,
            business: false,
            duration: '5 hours',
            rating: null,
            review: null,
            price: 'From CHF75/person',
            places: ['Utrecht'],
            isFavorite: true,
          },
        ],
      },
    ],

    wishlisted: [
      {
        title: 'June',
        data: [
          {
            id: 7,
            title: 'Outdoor yoga',
            photo: require('@assets/images/yoga.jpg'),
            date: '02/06/2023',
            business: true,
            duration: '3 days',
            rating: '3.88',
            review: 17,
            price: 'FREE',
            places: ['Utrecht'],
            isFavorite: true,
          },
          {
            id: 8,
            title: 'Cycling',
            photo: require('@assets/images/cycling.jpg'),
            date: '15/06/2024',
            new: true,
            business: false,
            duration: '5 hours',
            rating: null,
            review: null,
            price: 'From CHF75/person',
            places: ['Utrecht'],
            isFavorite: true,
          },
        ],
      },
      {
        title: 'July',
        data: [
          {
            id: 9,
            title: 'Hiking',
            photo: require('@assets/images/hiking.jpg'),
            date: '15/07/2024',
            new: true,
            business: false,
            duration: '5 hours',
            rating: null,
            review: null,
            price: 'From CHF75/person',
            places: ['Utrecht'],
            isFavorite: true,
          },
        ],
      },
    ],
  },
};
